- name: Clone the repository
  ansible.builtin.git:
    repo: "https://github.com/NathanFouere/in-browser-microservice"
    dest: "/root/in-browser-microservice"
    version: main
    force: yes

- name: Générer .env
  ansible.builtin.template:
    src: templates/.env.j2
    dest: /root/in-browser-microservice/.env

- name: Start the application
  community.docker.docker_compose_v2:
    project_src: "/root/in-browser-microservice"
    state: present
    build: always
